import re
import requests
import json
import matplotlib.pyplot as plt

# =========================
# TEXT NORMALIZER
# =========================
class TextNormalizer:
    @staticmethod
    def normalize(text):
        text = text.lower()
        text = re.sub(r'\s+', ' ', text)
        return text


# =========================
# NUTRITION EXTRACTOR
# =========================
class NutritionExtractor:
    @staticmethod
    def extract(text):
        patterns = {
            "calories": r'calories[:\s]*([\d\.]+)',
            "fat": r'fat[:\s]*([\d\.]+)',
            "protein": r'protein[:\s]*([\d\.]+)',
            "carbs": r'carbs?[:\s]*([\d\.]+)',
            "sodium": r'sodium[:\s]*([\d\.]+)'
        }

        data = {}
        for key, pattern in patterns.items():
            match = re.search(pattern, text)
            data[key] = float(match.group(1)) if match else None

        return data


# =========================
# HEALTH ANALYSIS
# =========================
def analyze_health(data):
    score = 5
    insights = []

    protein = data.get("protein") or 0
    carbs = data.get("carbs") or 0
    fat = data.get("fat") or 0
    sodium = data.get("sodium") or 0

    if protein > 10:
        score += 2
    else:
        insights.append("Low protein")

    if carbs > 40:
        score -= 2
        insights.append("High carbs")

    if fat > 20:
        score -= 1
        insights.append("High fat")

    if sodium > 500:
        score -= 2
        insights.append("High sodium")

    score = max(1, min(10, score))

    return {
        "score": score,
        "insights": insights
    }


# =========================
# DIET RECOMMENDATION
# =========================
def recommend_diet(data):
    diets = []

    carbs = data.get("carbs") or 0
    protein = data.get("protein") or 0

    if carbs < 20:
        diets.append("Low carb friendly")

    if protein > 10:
        diets.append("Muscle gain")

    if not diets:
        diets.append("Balanced diet")

    return diets


# =========================
# CONFIDENCE
# =========================
def calculate_confidence(data):
    total = len(data)
    found = sum(1 for v in data.values() if v is not None)
    return round((found / total) * 100, 2)


# =========================
# QWEN MODEL
# =========================
class QwenModel:
    @staticmethod
    def ask(prompt):
        try:
            response = requests.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": "qwen2.5:3b",
                    "prompt": prompt,
                    "stream": False
                },
                timeout=60
            )

            result = response.json()
            text = result.get("response", "")

            # Clean JSON
            if "{" in text and "}" in text:
                text = text[text.find("{"):text.rfind("}")+1]
                try:
                    return json.loads(text)
                except:
                    pass

            return {
                "answer": text.strip(),
                "reason": "Generated by model"
            }

        except Exception as e:
            return {
                "answer": "Model error",
                "reason": str(e)
            }


# =========================
# PROMPT BUILDER
# =========================
def build_prompt(data, question):
    return f"""
You are a nutrition expert.

Answer ONLY using the given data.

Data:
Calories: {data.get('calories')}
Fat: {data.get('fat')}
Protein: {data.get('protein')}
Carbs: {data.get('carbs')}
Sodium: {data.get('sodium')}

Question:
{question}

Rules:
- Be short (1–2 lines)
- Give clear reason
- Return JSON

Format:
{{"answer": "...", "reason": "..."}}
"""


# =========================
# QUESTION ANSWERING
# =========================
def answer_questions(data, questions):
    answers = {}

    for q in questions:
        q_lower = q.lower()

        if "calorie" in q_lower:
            answers[q] = f"{data.get('calories')} kcal"

        elif "protein" in q_lower:
            answers[q] = f"{data.get('protein')} g"

        elif "fat" in q_lower:
            fat = data.get("fat") or 0
            if fat > 20:
                answers[q] = "High"
            elif fat > 10:
                answers[q] = "Moderate"
            else:
                answers[q] = "Low"

        else:
            prompt = build_prompt(data, q)
            answers[q] = QwenModel.ask(prompt)

    return answers


# =========================
# RANK PRODUCTS
# =========================
def rank_products(results):
    ranked = []

    for i, item in enumerate(results):
        data = item["data"]
        health = analyze_health(data)

        ranked.append({
            "product": f"Product {i+1}",
            "score": health["score"],
            "insights": health["insights"],
            "data": data
        })

    ranked.sort(key=lambda x: x["score"], reverse=True)
    return ranked


# =========================
# EXPLAIN WINNER
# =========================
def explain_winner(ranking):
    best = ranking[0]

    reason = f"{best['product']} is the healthiest because:\n"

    if best["data"]["protein"] > 10:
        reason += "- High protein\n"

    if best["data"]["carbs"] < 30:
        reason += "- Lower carbs\n"

    if best["data"]["sodium"] < 300:
        reason += "- Low sodium\n"

    if best["data"]["fat"] < 15:
        reason += "- Moderate fat\n"

    return {
        "winner": best["product"],
        "score": best["score"],
        "reason": reason
    }


# =========================
# VISUAL COMPARISON
# =========================
def plot_comparison(products):
    labels = [f"P{i+1}" for i in range(len(products))]
    calories = [p["calories"] for p in products]
    protein = [p["protein"] for p in products]
    carbs = [p["carbs"] for p in products]

    x = range(len(products))

    plt.figure()
    plt.bar(x, calories)
    plt.xticks(x, labels)
    plt.title("Calories Comparison")

    plt.figure()
    plt.bar(x, protein)
    plt.xticks(x, labels)
    plt.title("Protein Comparison")

    plt.figure()
    plt.bar(x, carbs)
    plt.xticks(x, labels)
    plt.title("Carbs Comparison")

    plt.show()